# Exercice 2 - Les villes

Importer la base des villes villes.xls

Les noms de variables et les observations contiennent des espaces inutiles (exemple : ‘MAJ’) : commencer par nettoyer l’ensemble des chaines de caractères (à la fois dans les noms de colonnes et dans les observations)

Trouver le nombre de codes INSEE différents (attention aux doublons)

Comment calculer rapidement la moyenne, le nombre et le maximum pour chaque variable numérique ? (une ligne de code)

Compter le nombre de villes dans chaque Region et en faire un dictionnaire où la clé est la région et la valeur le nombre de villes

Représenter les communes en utilisant

#matplotlib (PAS NECESSAIRE POUR L'INSTANT mais scatter à utiliser en utilisant la longitude et la latitude)

#une librairie de cartographie (ex : folium) (BONUS POUR l'instant, on abordera le sujet) (https://france-geojson.gregoiredavid.fr/)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataframe = pd.read_csv("villes.txt", "\t")
dataframe

,Nom Ville,MAJ,Code Postal,Code INSEE,Code Région,Latitude,Longitude,Eloignement
0,L'Abergement-Clémenciat,L ABERGEMENT CLEMENCIAT,1400,1001,82,46.150000,4.916667,1.46
1,L'Abergement-de-Varey,L ABERGEMENT DE VAREY,1640,1002,82,46.000000,5.416667,1
2,Amareins,AMAREINS,1090,1003,82,46.083333,4.8,1.85
3,Ambérieu-en-Bugey,AMBERIEU EN BUGEY,1500,1004,82,45.950000,5.35,0.8
4,Ambérieux-en-Dombes,AMBERIEUX EN DOMBES,1330,1005,82,46.000000,4.9,1.72
...,...,...,...,...,...,...,...,...
35244,Saint-Michel,SAINT MICHEL,9100,9271,0,43.135000,1.5025,NaN
35245,Lorp-Sentaraille,LORP SENTARAILLE,9190,9289,0,43.008888,1.119444,NaN
35246,Soueix-Rogalle,SOUEIX ROGALLE,9140,9299,0,42.893333,1.211388,NaN
35247,Soulan,SOULAN,9320,9301,0,42.913333,1.233055,NaN
35248,Villeneuve,VILLENEUVE,9800,9335,0,42.938333,0.981666,NaN

In [3]:
dataframe.rename(columns=lambda x: x.strip(), inplace=True)
list(dataframe)

['Nom Ville',
 'MAJ',
 'Code Postal',
 'Code INSEE',
 'Code Région',
 'Latitude',
 'Longitude',
 'Eloignement']

In [4]:
list(dataframe['Code INSEE'].unique())

[1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1009,
 1010,
 1011,
 1012,
 1013,
 1014,
 1015,
 1016,
 1017,
 1019,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 1031,
 1032,
 1033,
 1034,
 1035,
 1037,
 1038,
 1039,
 1040,
 1041,
 1042,
 1043,
 1044,
 1045,
 1046,
 1047,
 1048,
 1049,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 1057,
 1058,
 1059,
 1060,
 1062,
 1064,
 1065,
 1066,
 1067,
 1068,
 1069,
 1070,
 1071,
 1072,
 1073,
 1074,
 1075,
 1076,
 1077,
 1078,
 1079,
 1080,
 1081,
 1082,
 1083,
 1084,
 1085,
 1086,
 1087,
 1088,
 1089,
 1090,
 1091,
 1092,
 1093,
 1094,
 1095,
 1096,
 1097,
 1098,
 1099,
 1100,
 1101,
 1102,
 1103,
 1104,
 1105,
 1106,
 1107,
 1108,
 1109,
 1110,
 1111,
 1112,
 1113,
 1114,
 1115,
 1116,
 1117,
 1118,
 1119,
 1120,
 1121,
 1122,
 1123,
 1124,
 1125,
 1127,
 1128,
 1129,
 1130,
 1131,
 1133,
 1134,
 1136,
 1137,
 1138,
 1139,
 1140,
 1142,
 1143,
 1144,
 1145,
 1146,
 1147,
 1148,
 1149,
 1150,
 1151,
 1153,
 1154,
 1155,
 1156,
 1157,
 1158,
 1159,
 1160,
 1161,
 1162,
 1163,
 1165,
 1166,
 1167,
 1169,
 1170,
 1171,
 1172,
 1173,
 1174,
 1175,
 1176,
 1177,
 1178,
 1179,
 1180,
 1181,
 1182,
 1183,
 1184,
 1185,
 1186,
 1187,
 1188,
 1189,
 1190,
 1191,
 1192,
 1193,
 1194,
 1195,
 1196,
 1197,
 1198,
 1199,
 1200,
 1202,
 1203,
 1204,
 1205,
 1206,
 1207,
 1208,
 1209,
 1210,
 1211,
 1212,
 1213,
 1214,
 1216,
 1217,
 1218,
 1219,
 1221,
 1223,
 1224,
 1225,
 1226,
 1227,
 1228,
 1229,
 1230,
 1231,
 1232,
 1233,
 1234,
 1235,
 1236,
 1237,
 1238,
 1239,
 1240,
 1241,
 1242,
 1244,
 1245,
 1246,
 1247,
 1248,
 1250,
 1251,
 1252,
 1253,
 1254,
 1255,
 1257,
 1258,
 1259,
 1260,
 1261,
 1262,
 1263,
 1264,
 1266,
 1268,
 1269,
 1270,
 1271,
 1272,
 1273,
 1274,
 1276,
 1277,
 1278,
 1279,
 1280,
 1281,
 1282,
 1283,
 1284,
 1285,
 1286,
 1287,
 1288,
 1289,
 1290,
 1291,
 1292,
 1293,
 1295,
 1296,
 1297,
 1298,
 1299,
 1300,
 1301,
 1302,
 1303,
 1304,
 1305,
 1306,
 1307,
 1308,
 1309,
 1310,
 1311,
 1312,
 1313,
 1314,
 1316,
 1317,
 1318,
 1319,
 1320,
 1321,
 1322,
 1323,
 1324,
 1325,
 1327,
 1328,
 1329,
 1330,
 1331,
 1332,
 1333,
 1334,
 1335,
 1336,
 1337,
 1338,
 1340,
 1341,
 1343,
 1344,
 1345,
 1346,
 1347,
 1348,
 1349,
 1350,
 1351,
 1352,
 1353,
 1354,
 1355,
 1356,
 1357,
 1358,
 1359,
 1360,
 1361,
 1362,
 1364,
 1365,
 1366,
 1367,
 1368,
 1370,
 1372,
 1373,
 1374,
 1375,
 1376,
 1378,
 1379,
 1380,
 1381,
 1382,
 1383,
 1384,
 1385,
 1386,
 1388,
 1389,
 1390,
 1391,
 1392,
 1393,
 1396,
 1397,
 1398,
 1399,
 1400,
 1401,
 1402,
 1404,
 1405,
 1406,
 1408,
 1409,
 1410,
 1411,
 1412,
 1413,
 1414,
 1415,
 1416,
 1417,
 1418,
 1420,
 1421,
 1422,
 1423,
 1424,
 1425,
 1427,
 1428,
 1429,
 1430,
 1431,
 1432,
 1433,
 1434,
 1436,
 1437,
 1439,
 1440,
 1441,
 1442,
 1443,
 1444,
 1445,
 1447,
 1448,
 1451,
 1452,
 1453,
 1454,
 1455,
 1456,
 1457,
 1458,
 1909,
 1910,
 1911,
 1912,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 2025,
 2026,
 2027,
 2028,
 2029,
 2030,
 2031,
 2032,
 2033,
 2034,
 2035,
 2036,
 2037,
 2038,
 2039,
 2040,
 2041,
 2042,
 2043,
 2044,
 2045,
 2046,
 2047,
 2048,
 2050,
 2051,
 2052,
 2053,
 2055,
 2056,
 2057,
 2058,
 2059,
 2060,
 2062,
 2063,
 2064,
 2065,
 2066,
 2067,
 2069,
 2070,
 2071,
 2072,
 2073,
 2074,
 2075,
 2076,
 2077,
 2078,
 2079,
 2080,
 2081,
 2082,
 2083,
 2084,
 2085,
 2086,
 2087,
 2088,
 2089,
 2090,
 2091,
 2093,
 2094,
 2095,
 2096,
 2097,
 2098,
 2099,
 2100,
 2101,
 2103,
 2104,
 2105,
 2106,
 2107,
 2109,
 2110,
 2111,
 2112,
 2113,
 2114,
 2115,
 2116,
 2117,
 2118,
 2119,
 2120,
 2121,
 2123,
 2125,
 2126,
 2127,
 2128,
 2129,
 2130,
 2131,
 2132,
 2133,
 2134,
 2135,
 2136,
 2137,
 2138,
 2139,
 2142,
 2143,
 2144,
 2145,
 2146,
 2148,
 2149,
 2150,
 2151,
 2152,
 2153,
 2154,
 2155,
 2156,
 2157,
 2158,
 2159,
 2160,
 2161,
 2162,
 2164,
 2165,
 2166,
 2167,
 2168,
 2169,
 2170,
 2171,
 2172,
 2173,
 2174,
 2175,
 2176,
 2177,
 2178,
 2179,
 2180,
 2181,
 2182,
 2183,
 2184,
 2185,
 2186,
 2187,
 2188,
 2189,
 2190,
 2191,
 2192,
 2193,
 2194,
 2195,
 2196,
 2197,
 2198,
 2199,
 2200,
 2201,
 2202,
 2203,
 2204,
 2205,
 2206,
 2207,
 2208,
 2209,
 2210,
 2211,
 2212,
 2213,
 2214,
 2215,
 2216,
 2218,
 2219,
 2221,
 2222,
 2223,
 2225,
 2226,
 2227,
 2228,
 2229,
 2230,
 2231,
 2232,
 2233,
 2234,
 2235,
 2236,
 2237,
 2239,
 2240,
 2241,
 2243,
 2244,
 2245,
 2246,
 2247,
 2248,
 2249,
 2250,
 2252,
 2253,
 2254,
 2255,
 2256,
 2257,
 2258,
 2259,
 2260,
 2261,
 2262,
 2263,
 2264,
 2265,
 2266,
 2267,
 2268,
 2269,
 2270,
 2271,
 2272,
 2274,
 2275,
 2276,
 2277,
 2278,
 2279,
 2280,
 2281,
 2282,
 2283,
 2284,
 2285,
 2286,
 2287,
 2288,
 2289,
 2290,
 2291,
 2292,
 2293,
 2294,
 2295,
 2296,
 2297,
 2298,
 2299,
 2300,
 2301,
 2303,
 2304,
 2305,
 2306,
 2307,
 2309,
 2310,
 2311,
 2312,
 2315,
 2317,
 2318,
 2319,
 2320,
 2321,
 2322,
 2323,
 2324,
 2325,
 2326,
 2327,
 2328,
 2329,
 2330,
 2332,
 2334,
 2335,
 2336,
 2337,
 2338,
 2339,
 2340,
 2341,
 2342,
 2343,
 2344,
 2345,
 2346,
 2347,
 2348,
 2351,
 2353,
 2354,
 2355,
 2356,
 2357,
 2358,
 2359,
 2360,
 2361,
 2362,
 2363,
 2364,
 2366,
 2367,
 2368,
 2369,
 2371,
 2372,
 2373,
 2374,
 2375,
 2376,
 2377,
 2378,
 2379,
 2380,
 2381,
 2382,
 2383,
 2384,
 2385,
 2386,
 2387,
 2388,
 2389,
 2390,
 2391,
 2392,
 2393,
 2394,
 2395,
 2396,
 2397,
 2398,
 2399,
 2400,
 2401,
 2402,
 2403,
 2404,
 2405,
 2406,
 2407,
 2408,
 2409,
 2410,
 2411,
 2412,
 2413,
 2414,
 2415,
 2416,
 2417,
 2418,
 2419,
 2420,
 2421,
 2422,
 2423,
 2424,
 2425,
 2426,
 2427,
 2428,
 2429,
 2431,
 2432,
 2433,
 2434,
 2435,
 2436,
 2437,
 2438,
 2440,
 2441,
 2442,
 2443,
 2444,
 2445,
 2446,
 2447,
 2448,
 2449,
 2450,
 2451,
 2452,
 2453,
 2454,
 2455,
 2456,
 2457,
 2458,
 2459,
 2460,
 2461,
 2462,
 2463,
 2464,
 2465,
 2466,
 2467,
 2468,
 2469,
 2470,
 2471,
 2472,
 2473,
 2474,
 2475,
 2476,
 2477,
 2478,
 2479,
 2480,
 2481,
 2482,
 2483,
 2484,
 2485,
 2486,
 2487,
 2488,
 2489,
 2490,
 2492,
 2493,
 2494,
 2495,
 2496,
 2498,
 2499,
 2500,
 2501,
 2503,
 2505,
 2506,
 2507,
 2508,
 2509,
 2510,
 2511,
 2512,
 2513,
 2514,
 2515,
 2516,
 2517,
 2518,
 2519,
 2520,
 2521,
 2522,
 2523,
 2524,
 2525,
 2526,
 2527,
 2529,
 2530,
 2531,
 2532,
 2533,
 2534,
 2535,
 2536,
 2537,
 2538,
 2539,
 2540,
 2541,
 2542,
 2543,
 2544,
 2545,
 2546,
 2547,
 2548,
 2549,
 2550,
 2551,
 2552,
 2553,
 2554,
 2555,
 2556,
 2557,
 2558,
 2559,
 2560,
 2561,
 2562,
 2563,
 2564,
 2565,
 2567,
 2568,
 2569,
 2570,
 2571,
 2572,
 2573,
 2574,
 2575,
 2576,
 2577,
 2578,
 2579,
 2580,
 2581,
 2582,
 2583,
 2584,
 2586,
 2587,
 2588,
 2589,
 2590,
 2591,
 2592,
 2593,
 2594,
 2595,
 2596,
 2597,
 2598,
 2599,
 2600,
 2601,
 2602,
 2603,
 2604,
 2605,
 2606,
 2607,
 2608,
 2610,
 2611,
 2612,
 2613,
 2614,
 2615,
 2616,
 2617,
 2618,
 2619,
 2620,
 2621,
 2622,
 2623,
 2624,
 2625,
 ...]

In [5]:
dataframe.describe()

        Code Postal    Code INSEE   Code Région      Latitude
count  35249.000000  35249.000000  35249.000000  35249.000000
mean   46291.014554  46186.992822     48.532497     46.998450
std    25418.598824  25411.240496     27.264257      2.206877
min     1000.000000   1001.000000      0.000000     41.391667
25%    24640.000000  24550.000000     24.000000     45.216667
50%    49150.000000  49074.000000     43.000000     47.450000
75%    66720.000000  66203.000000     72.000000     48.850000
max    95880.000000  95690.000000     94.000000     51.083333

In [6]:
dataframe.groupby('Code Région')[['Nom Ville']].size()

Code Région
0       86
11    4181
21    1462
22    1433
23    1342
24    1766
25    1774
26    1483
31    1494
41    1825
43    1104
52    1188
53    1243
54     830
72    5450
73    1535
74     837
82    2368
83     977
91    1871
93     662
94     338
dtype: int64